name: watermaniac
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: "^0.5.2"
  # sensors: "^0.3.5"
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  sqflite: ^0.13.0
  intl: ^0.15.7
  flutter_svg: ^0.7.0+1
  # quick_actions: ^0.2.1
  flutter_local_notifications: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/buttons/
    - assets/icons/
    - assets/background/
